### ISSUE TITLE
Error while generating moment equations using catalyst

### ISSUE THREAD

**Issue by btemoshir** [augustinas1/MomentClosure.jl#11]
There is an issue after I reinstalled the Julia package, so this was likley to be during the last commit. If I use catalyst to define a simple system and try to generate the moment equations, I get errors saying Non-polynomial propensity function was included/and or a bug.

```julia
using Catalyst
rn = @reaction_network begin
  (k3), A + B → C
  (k1A, k2A), 0 ↔ A
  (k1B, k2B), 0 ↔ B
  (k1C, k2C), 0 ↔ C
    
end k1A k2A k1B k2B k1C k2C k3
```

```julia
using MomentClosure
raw_eqs = generate_raw_moment_eqs(rn, 2, combinatoric_ratelaw=false)
central_eqs = generate_central_moment_eqs(rn, 2, combinatoric_ratelaw=false)
```

**Comment by augustinas1** [comment]
Hi @btemoshir, most recent versions of some of the dependencies introduced breaking changes - I've resolved them now, let me know if it's working for you!

**Comment by btemoshir** [comment]
Hi @augustinas1 thank you so much for the resolution. It works great again!
