### ISSUE TITLE
Migrate to newer versions of SymbolicUtils

### ISSUE THREAD

**Issue by kaandocal** [augustinas1/MomentClosure.jl#26]
As noted in [this issue](https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/330) MomentClosure.jl does not work with SymbolicUtils.jl version 0.13 or higher. I've created a branch 3a33912e1296b900614558028ff0de1ffb52640b that reflects this.

**Comment by augustinas1** [comment]
Thanks very much Kaan! I've adopted many of your nice changes and finally updated the compat.  Keeping this open as not everything works: SymbolicUtils added fraction functionality which breaks any symbolic expression containing "/", have to use "^-1" instead for the time being. Will try to patch this up when it's a little bit more stable on their side. Got to also rerun all the examples to see whether I missed anything else.
