### ISSUE TITLE
Add package to Julia registry

### ISSUE THREAD

**Issue by kaandocal** [augustinas1/MomentClosure.jl#40]

**Comment by jamesholehouse** [comment]
Yes @kaandocal, I completely agree this needs to be on the registry. I use this package quite a lot and it would make it much easier for others to use.

**Comment by augustinas1** [comment]
@JuliaRegistrator register

**Comment by augustinas1** [comment]
enjoy

**Comment by augustinas1** [comment]
@JuliaRegistrator register

**Comment by augustinas1** [comment]
@JuliaRegistrator register

**Comment by augustinas1** [comment]
@JuliaRegistrator register
