### ISSUE TITLE
Can't precompile MomentClosure.jl

### ISSUE THREAD

**Issue by sdwfrost** [augustinas1/MomentClosure.jl#5]
I'm trying to run my example code, which worked previously:

[https://github.com/epirecipes/sir-julia/blob/master/markdown/momentclosure/momentclosure.md](https://github.com/epirecipes/sir-julia/blob/master/markdown/momentclosure/momentclosure.md)

but I either get a precompilation error (as above), or a `LoadError: syntax: malformed expression`.

**Comment by augustinas1** [comment]
Sorry about that! I thought updating the versions of dependencies will suffice but this seems to be some weird clash of method definitions between ModelingToolkit and Symbolics. Will push a fix shortly

**Comment by augustinas1** [comment]
OK it seems that `@reexport` has broken for some reason, removed it and the package precompiles fine (at least for me). Let me know if it's now working for you @sdwfrost.

**Comment by sdwfrost** [comment]
Thanks @augustinas1! It recompiles now.
