### ISSUE TITLE
Updating to new SymbolicUtils version

### ISSUE THREAD

**Issue by pogudingleb** [augustinas1/MomentClosure.jl#53]
Thank you for your package!
There has been a [breaking release](https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/page/upgrade.md) for `SymbolicUtils` recently. I wonder if you could update your package to it. Thank you in advance!

**Comment by augustinas1** [comment]
Hi, yeah the update is long overdue but finally in progress (see #48). Will merge it soon!

**Comment by pogudingleb** [comment]
Cool, thanks!

**Comment by augustinas1** [comment]
Should be working now
